# Welcome to Jekyll!
#

# Site settings
title: Go-To
description: The Go-To Event App
 Enhance your Event Experience
cta: Get in touch
scroll_for_more: What we can do
## Main section ##
main_section_title: Great events need even greater apps
main_section_text: Why you need an app...
## Interest ##
interested_title: Interested?
interested_text: If you'd like to find out more about how to get setup or want us to be your Go-To, get in touch today.

owner: Go-To # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: rob+eventee@iamrobj.com
baseurl: 
url: "http://getstuffd.london/" # the base hostname & protocol for your site
social:
  twitter: http://twitter.com/getstuffdldn
  instagram: http://instagram.com/getstuffdldn
  #github: 
  #linkedin-square: 
  #facebook-official: 
  #google-plus-square: 
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
